### PR TITLE
Allow installing a zipped addon

### PR DESCRIPTION
**Pull request by karlisup**
Removes a limitation of an addon as a python file only installation and enables to install .zip file.

With these changes it is possible to install _.zip_ version of an addon like so:
`addon_module_names = install_addons_from_dir(addons_dir, ['youraddon.zip'])`

More information in the [issue](https://github.com/mondeja/pytest-blender/issues/51).

### CODE REVIEW

**Comment by mondeja** [comment]
Could you add a test, please?

**Comment by karlisup** [comment]
Sure thing! A few days ago I noticed another issue that I would love to include in the fix if you don't mind. Currently, if the file is provided with version postfix e.g. `myaddon-1.2.3.zip` addon is installed correctly, but as the addon file name gets trimmed in order to achieve the addon name which for some reason becomes `myaddon-` which isn't correct.

I do think that the proposed quick-fix for supporting .zip files becomes obsolete and a new approach fixing the issue is required.

**Comment by karlisup** [comment]
As requested added integration tests regarding archived addons and addons with version postfixes. I would appreciate it if you would have time to review them and give feedback.

**Comment by mondeja** [comment]
Don't worry, I'm digging into this right now 👍🏼

**Comment by mondeja** [comment]
Superseded by #53

**Comment by karlisup** [comment]
Thank you for taking the time to fix this! Went through the changelog and will try this tomorrow. Adding disable+uninstall add-ons after the tests have been executed is an excellent addition to the changes - thanks!

**Pull request closed without merging**
